### User Login
POST {{address}}/api/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "123"
}

### User Register
POST {{address}}/api/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "username": "test",
  "password": "123"
}