### Country Create
POST {{address}}/api/country/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Thailand"
}

### Country Get
GET {{address}}/api/country/get
Authorization: Bearer {{token}}

### Country Update
PUT {{address}}/api/country/update/5907ed43-4a29-431c-9c8a-96e5995c2952
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "United States of America"
}

### Country Assign User
PUT {{address}}/api/country/assign
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "countryId": "fda452b3-7e5d-4091-8e41-4a3c357c593f",
  "userId": "31c1b25d-a1fb-4480-83dd-b64d5d131ea4"
}

### Country Unassign User
PUT {{address}}/api/country/unassign
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "f97ae493-dcb0-4dac-a43f-60548c96fa17"
}

### Users By Country
GET {{address}}/api/country/get/fda452b3-7e5d-4091-8e41-4a3c357c593f
Authorization: Bearer {{token}}

### Delete Country
DELETE {{address}}/api/country/delete/fda452b3-7e5d-4091-8e41-4a3c357c593f
Authorization: Bearer {{token}}
