### Get Posts
GET {{address}}/api/post/get
Authorization: Bearer {{token}}

### Get Posts w/ User ID
GET {{address}}/api/post/get?userId=035c02a9-7432-4199-8e98-55142410f215
Authorization: Bearer {{token}}

### Get Posts by date range
GET {{address}}/api/post/get?dateFrom=2019-01-01&dateTo=2023-05-01
Authorization: Bearer {{token}}

### Get Posts by date range expected no data
GET {{address}}/api/post/get?dateFrom=2019-01-01&dateTo=2022-04-01
Authorization: Bearer {{token}}

### Create Post
POST {{address}}/api/post/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Post Title",
    "content": "Post Content"
}

### Update Post
PUT {{address}}/api/post/update/fd5fb53a-67ce-4d8d-b18a-2bf41dd10128
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Post Title2",
    "content": "Post Content2"
}

### Delete Post
DELETE {{address}}/api/post/delete/fd5fb53a-67ce-4d8d-b18a-2bf41dd10128
Authorization: Bearer {{token}}
